### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_active'

### ISSUE THREAD

**Issue by mattrobenolt** [wee-slack/wee-slack#309]
Using latest version (01beb42fec5c6dbfc0d8c53ce1de88b48b48f6db) I get the following spewed into my weechat console:

```
09:13:21  weechat        | python: stdout/stderr: Traceback (most recent call last):
09:13:21  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 1558, in slack_websocket_cb
09:13:21  weechat        | python: stdout/stderr:     proc[function_name](message_json)
09:13:21  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 1616, in process_presence_change
09:13:21  weechat        | python: stdout/stderr:     server.users.find(identifier).set_active()
09:13:21  weechat        | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'set_active'
09:13:21  weechat    =!= | python: error in function "slack_websocket_cb"
```

I'm not 100% what action triggers this.

**Comment by mattrobenolt** [comment]
Dang, I keep forgetting this. Related to https://github.com/wee-slack/wee-slack/issues/275

Definitely happened after `/upgrade`
