### ISSUE TITLE
TypeError: must be string, not None

### ISSUE THREAD

**Issue by mattrobenolt** [wee-slack/wee-slack#310]
Using latest version (01beb42fec5c6dbfc0d8c53ce1de88b48b48f6db) I get the following spewed into my weechat console:

```
09:17:33  weechat    =!= | python: wrong arguments for function "nicklist_add_nick" (script: slack_extension)
09:17:33  weechat    =!= | python: wrong arguments for function "nicklist_nick_set" (script: slack_extension)
09:17:33  weechat        | python: stdout/stderr: Traceback (most recent call last):
09:17:33  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 2316, in url_processor_cb
09:17:33  weechat        | python: stdout/stderr:     servers.find(data["token"]).connected_to_slack(my_json)
09:17:33  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 266, in connected_to_slack
09:17:33  weechat        | python: stdout/stderr:     self.create_slack_mappings(login_data)
09:17:33  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 331, in create_slack_mappings
09:17:33  weechat        | python: stdout/stderr:     self.add_user(User(self, item["name"], item["id"], item["presence"], item["deleted"], is_bot=item.get('is_bot', False)))
09:17:33  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 183, in add_user
09:17:33  weechat        | python: stdout/stderr:     self.users.append(user, user.get_aliases())
09:17:33  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 104, in append
09:17:33  weechat        | python: stdout/stderr:     self.update_hashtable(item)
09:17:33  weechat        | python: stdout/stderr:   File "/home/matt/.weechat/python/autoload/wee_slack.py", line 109, in update_hashtable
09:17:33  weechat        | python: stdout/stderr:     for alias in item.get_aliases():
09:17:33  weechat        | python: stdout/stderr: TypeError: must be string, not None
09:17:33  weechat    =!= | python: error in function "url_processor_cb"
```

I'm not 100% what action triggers this.

This also seems to always happen right before #309

**Comment by mattrobenolt** [comment]
Dang, I keep forgetting this. Related to https://github.com/wee-slack/wee-slack/issues/275

Definitely happened after `/upgrade`
