### ISSUE TITLE
Enterprise Grid support ?

### ISSUE THREAD

**Issue by d3xt3r01** [wee-slack/wee-slack#361]
So, the team migrated to an enterprise grid account .. 
Just got the latest wee-slack.py and nothing showed up ! Just nothing happened.
Setting wee-slack on debug mode yelled this:
```
23:23:13                weechat     | python: stdout/stderr: Traceback (most recent call last):
23:23:13                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 464, in handle_next
23:23:13                weechat     | python: stdout/stderr:     EVENTROUTER.handle_next()
23:23:13                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 452, in handle_next
23:23:13                weechat     | python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
23:23:13                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 2028, in handle_rtmstart
23:23:13                weechat     | python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
23:23:13                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1523, in __init__
23:23:13                weechat     | python: stdout/stderr:     kwargs["name"] = users[dmuser].name
23:23:13                weechat     | python: stdout/stderr: KeyError: u'W4A0EM54K'
```
Not much of a coder but here's how I got past this issue:

Added a prettyprint in __init__ in SlackDMChannel to see kwargs and set kwargs["name"] = 'myusername'
Now stuff seems to work. Keeping debug a little bit showed up some more traces:

```
23:49:07  BlackBishop | 23:48:43                weechat     | python: stdout/stderr: ProcessNotImplemented: immark
23:49:20  BlackBishop | 23:48:42                weechat     | python: stdout/stderr: ProcessNotImplemented: channelsmark
23:49:41  BlackBishop | 23:47:47                weechat     | python: stdout/stderr: ProcessNotImplemented: user_change
23:49:58  BlackBishop | 23:48:20                weechat     | python: stdout/stderr: ProcessNotImplemented: groupsmark
23:50:25  BlackBishop | 23:49:38                weechat     | python: stdout/stderr: ProcessNotImplemented: pin_added
23:50:35  BlackBishop | 23:49:29                weechat     | python: stdout/stderr: ProcessNotImplemented: file_shared
23:50:42  BlackBishop | 23:49:29                weechat     | python: stdout/stderr: ProcessNotImplemented: file_public
```
Let me know if there's anything I can help you with debug/implement/fix the issue.

**Comment by jpeeler** [comment]
I'm seeing something similar. I realized I wasn't running the latest (about 10 commits older), so I updated but am still seeing the messages.

```
python: stdout/stderr: ProcessNotImplemented: apps_changed
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 472, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 462, in handle_next
python: stdout/stderr:     raise ProcessNotImplemented(function_name)
python: stdout/stderr: ProcessNotImplemented: bot_added
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 472, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 462, in handle_next
python: stdout/stderr:     raise ProcessNotImplemented(function_name)
python: stdout/stderr: ProcessNotImplemented: apps_installed
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 472, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 462, in handle_next
python: stdout/stderr:     raise ProcessNotImplemented(function_name)
python: stdout/stderr: ProcessNotImplemented: immark
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 472, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 462, in handle_next
python: stdout/stderr:     raise ProcessNotImplemented(function_name)
python: stdout/stderr: ProcessNotImplemented: immark
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 472, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 462, in handle_next
python: stdout/stderr:     raise ProcessNotImplemented(function_name)
python: stdout/stderr: ProcessNotImplemented: channelsmark
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 472, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 462, in handle_next
python: stdout/stderr:     raise ProcessNotImplemented(function_name)
python: stdout/stderr: ProcessNotImplemented: apps_uninstalled
```
I've seen the plugin work a few times, but most of the time it wouldn't load. This is the first time I've checked any debug messaging.

However, more concerning is this error message on the slack-debug window:

```
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -1 of length 65528
2017-09-19 19:07:02             DEBUG: RECEIVED CALLBACK with request of rtm.start id of 332dc1dbc19fb44db49c0da55d36c72fe45bf801 and  code -2 of length 16382
2017-09-19 19:07:18             DEBUG: socket issue: Traceback (most recent call last):
2017-09-19 19:07:18               File "/home/jpeeler/.weechat/python/autoload/wee_slack.py", line 303, in receive_ws_callback
2017-09-19 19:07:18                 data = decode_from_utf8(self.teams[team_hash].ws.recv())
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 293, in recv
2017-09-19 19:07:18                 opcode, data = self.recv_data()
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 310, in recv_data
2017-09-19 19:07:18                 opcode, frame = self.recv_data_frame(control_frame)
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 323, in recv_data_frame
2017-09-19 19:07:18                 frame = self.recv_frame()
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 357, in recv_frame
2017-09-19 19:07:18                 return self.frame_buffer.recv_frame()
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 336, in recv_frame
2017-09-19 19:07:18                 self.recv_header()
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 286, in recv_header
2017-09-19 19:07:18                 header = self.recv_strict(2)
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 371, in recv_strict
2017-09-19 19:07:18                 bytes_ = self.recv(min(16384, shortage))
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 427, in _recv
2017-09-19 19:07:18                 return recv(self.sock, bufsize)
2017-09-19 19:07:18               File "/usr/lib/python2.7/site-packages/websocket/_socket.py", line 80, in recv
2017-09-19 19:07:18                 bytes_ = sock.recv(bufsize)
2017-09-19 19:07:18               File "/usr/lib64/python2.7/ssl.py", line 766, in recv
2017-09-19 19:07:18                 return self.read(buflen)
2017-09-19 19:07:18               File "/usr/lib64/python2.7/ssl.py", line 653, in read
2017-09-19 19:07:18                 v = self._sslobj.read(len)
2017-09-19 19:07:18             SSLWantReadError: The operation did not complete (read) (_ssl.c:1864)
```

**Comment by d3xt3r01** [comment]
Still have this problem .. Any chance I can help debug ? Maybe not to crash because of this .. if it's a chan problem maybe I can at least find out which one .. and go from there ?

**Comment by d3xt3r01** [comment]
@trygveaa an hour ago before askin' if there anything I can help with... with no luck.

```
22:16:27   weechat     | python: unloading script "bitlbee_typing_notice"
22:16:27   weechat     | python: unloading script "buffer_autoset"
22:16:27   weechat     | python: unloading script "shell"
22:16:27   weechat     | python: unloading script "slack"
22:16:27   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/bitlbee_typing_notice.py"
22:16:27   weechat     | python: registered script "bitlbee_typing_notice", version 0.5 (Shows when somebody is typing on bitlbee and sends the notice as well)
22:16:27   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/buffer_autoset.py"
22:16:27   weechat     | python: registered script "buffer_autoset", version 1.0 (Auto-set buffer properties when a buffer is opened)
22:16:27   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/shell.py"
22:16:27   weechat     | python: registered script "shell", version 0.8 (Run shell commands in WeeChat)
22:16:27   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/wee_slack.py"
22:16:27   weechat     | python: registered script "slack", version 2.0.0 (Extends weechat for typing notification/search/etc on slack.com)
22:16:27   weechat =!= | logger: unable to start logging for buffer "slack-debug": filename "/home/dexter/.weechat/logs/$server/$channel_20180520.log" is already used by another buffer (check your log settings)
22:16:32   weechat     | python: stdout/stderr: Traceback (most recent call last):
22:16:32   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 509, in handle_next
22:16:32   weechat     | python: stdout/stderr:     EVENTROUTER.handle_next()
22:16:32   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 497, in handle_next
22:16:32   weechat     | python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
22:16:32   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 2166, in handle_rtmstart
22:16:32   weechat     | python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
22:16:32   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1637, in __init__
22:16:32   weechat     | python: stdout/stderr:     kwargs["name"] = users[dmuser].name
22:16:32   weechat     | python: stdout/stderr: KeyError: u'W25653WGG'
22:21:44   weechat =!= | Option "slack.*" not found (tip: you can use wildcard "*" in option to see a sublist)
```

**Comment by trygveaa** [comment]
@d3xt3r01: What you're running is master, not the PR I linked to. Run this:

```
git fetch origin pull/462/merge
git checkout FETCH_HEAD
```

**Comment by d3xt3r01** [comment]
@trygveaa Thanks. Done .. no luck.

```
$ git fetch origin pull/462/merge

remote: Counting objects: 16, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 16 (delta 9), reused 12 (delta 9), pack-reused 1
Unpacking objects: 100% (16/16), done.
From https://github.com/wee-slack/wee-slack
 * branch            refs/pull/462/merge -> FETCH_HEAD
$ git checkout FETCH_HEAD

Note: checking out 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 413a71d Merge 523741133f5b12270bc251fe6324198d2a654f11 into f1d6fc7e5bd64e48ddd9a9aca1cdc985dfc2265c
```


```
23:45:05   weechat     | python: unloading script "bitlbee_typing_notice"
23:45:05   weechat     | python: unloading script "buffer_autoset"
23:45:05   weechat     | python: unloading script "shell"
23:45:05   weechat     | python: unloading script "slack"
23:45:05   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/bitlbee_typing_notice.py"
23:45:05   weechat     | python: registered script "bitlbee_typing_notice", version 0.5 (Shows when somebody is typing on bitlbee and sends the notice as well)
23:45:05   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/buffer_autoset.py"
23:45:05   weechat     | python: registered script "buffer_autoset", version 1.0 (Auto-set buffer properties when a buffer is opened)
23:45:05   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/shell.py"
23:45:05   weechat     | python: registered script "shell", version 0.8 (Run shell commands in WeeChat)
23:45:05   weechat     | python: loading script "/home/dexter/.weechat/python/autoload/wee_slack.py"
23:45:05   weechat     | python: registered script "slack", version 2.0.0 (Extends weechat for typing notification/search/etc on slack.com)
23:45:05   weechat =!= | logger: unable to start logging for buffer "slack-debug": filename "/home/dexter/.weechat/logs/$server/$channel_20180520.log" is already used by another buffer (check your log settings)
23:45:09   weechat     | python: stdout/stderr: Traceback (most recent call last):
23:45:09   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 509, in handle_next
23:45:09   weechat     | python: stdout/stderr:     EVENTROUTER.handle_next()
23:45:09   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 497, in handle_next
23:45:09   weechat     | python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
23:45:09   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 2166, in handle_rtmstart
23:45:09   weechat     | python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
23:45:09   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1637, in __init__
23:45:09   weechat     | python: stdout/stderr:     kwargs["name"] = users[dmuser].name
23:45:09   weechat     | python: stdout/stderr: KeyError: u'W25653WGG'
23:45:10   weechat     | python: stdout/stderr: Traceback (most recent call last):
23:45:10   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 509, in handle_next
23:45:10   weechat     | python: stdout/stderr:     EVENTROUTER.handle_next()
23:45:10   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 497, in handle_next
23:45:10   weechat     | python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
23:45:10   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 2166, in handle_rtmstart
23:45:10   weechat     | python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
23:45:10   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1637, in __init__
23:45:10   weechat     | python: stdout/stderr:     kwargs["name"] = users[dmuser].name
23:45:10   weechat     | python: stdout/stderr: KeyError: u'W25653WGG'
23:45:11   weechat     | python: stdout/stderr: Traceback (most recent call last):
23:45:11   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 509, in handle_next
23:45:11   weechat     | python: stdout/stderr:     EVENTROUTER.handle_next()
23:45:11   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 497, in handle_next
23:45:11   weechat     | python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
23:45:11   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 2166, in handle_rtmstart
23:45:11   weechat     | python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
23:45:11   weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1637, in __init__
23:45:11   weechat     | python: stdout/stderr:     kwargs["name"] = users[dmuser].name
23:45:11   weechat     | python: stdout/stderr: KeyError: u'W25653WGG'
```

**Comment by d3xt3r01** [comment]
@trygveaa sorry about that. My bad, forgot to update the autoload script.

**Comment by d3xt3r01** [comment]
```
23:49:16                weechat     | python: unloading script "bitlbee_typing_notice"
23:49:16                weechat     | python: unloading script "buffer_autoset"
23:49:16                weechat     | python: unloading script "shell"
23:49:16                weechat     | python: unloading script "slack"
23:49:16                weechat     | python: loading script "/home/dexter/.weechat/python/autoload/bitlbee_typing_notice.py"
23:49:16                weechat     | python: registered script "bitlbee_typing_notice", version 0.5 (Shows when somebody is typing on bitlbee and sends the notice as well)
23:49:16                weechat     | python: loading script "/home/dexter/.weechat/python/autoload/buffer_autoset.py"
23:49:16                weechat     | python: registered script "buffer_autoset", version 1.0 (Auto-set buffer properties when a buffer is opened)
23:49:16                weechat     | python: loading script "/home/dexter/.weechat/python/autoload/shell.py"
23:49:16                weechat     | python: registered script "shell", version 0.8 (Run shell commands in WeeChat)
23:49:16                weechat     | python: loading script "/home/dexter/.weechat/python/autoload/wee_slack.py"
23:49:16                weechat     | python: registered script "slack", version 2.0.0 (Extends weechat for typing notification/search/etc on slack.com)
23:49:16                weechat =!= | logger: unable to start logging for buffer "slack-debug": filename "/home/dexter/.weechat/logs/$server/$channel_20180520.log" is already used by another buffer (check your
                                    | log settings)
23:49:20 adobetechops.slack.com     | Connected to Slack
23:49:20 adobetechops.slack.com     | Websocket URL        
23:49:20 adobetechops.slack.com     | User name            
23:49:20 adobetechops.slack.com     | User ID              
23:49:20 adobetechops.slack.com     | Team domain          
23:49:20 adobetechops.slack.com     | Team id              
23:49:20                weechat     | python: stdout/stderr: Traceback (most recent call last):
23:49:20                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 126, in wrapper
23:49:20                weechat     | python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
23:49:20                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 741, in buffer_list_update_callback
23:49:20                weechat     | python: stdout/stderr:     b[1].refresh()
23:49:20                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1741, in refresh
23:49:20                weechat     | python: stdout/stderr:     return self.rename()
23:49:20                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1733, in rename
23:49:20                weechat     | python: stdout/stderr:     new_name = self.formatted_name(style="sidebar", present=self.team.is_user_present(self.user), enable_color=config.colorize_private_chats)
23:49:20                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1108, in is_user_present
23:49:20                weechat     | python: stdout/stderr:     if user.presence == 'active':
23:49:20                weechat     | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'presence'
23:49:20                weechat =!= | python: error in function "buffer_list_update_callback"
23:49:21                weechat     | python: stdout/stderr: Traceback (most recent call last):
23:49:21                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 126, in wrapper  
23:49:21                weechat     | python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
23:49:21                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 741, in buffer_list_update_callback
23:49:21                weechat     | python: stdout/stderr:     b[1].refresh()
23:49:21                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1741, in refresh   
23:49:21                weechat     | python: stdout/stderr:     return self.rename()
23:49:21                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1733, in rename
23:49:21                weechat     | python: stdout/stderr:     new_name = self.formatted_name(style="sidebar", present=self.team.is_user_present(self.user), enable_color=config.colorize_private_chats)
23:49:21                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1108, in is_user_present
23:49:21                weechat     | python: stdout/stderr:     if user.presence == 'active':
23:49:21                weechat     | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'presence'
23:49:21                weechat =!= | python: error in function "buffer_list_update_callback"
23:49:22                weechat     | python: stdout/stderr: Traceback (most recent call last):
23:49:22                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 126, in wrapper
23:49:22                weechat     | python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
23:49:22                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 741, in buffer_list_update_callback
23:49:22                weechat     | python: stdout/stderr:     b[1].refresh()
23:49:22                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1741, in refresh
23:49:22                weechat     | python: stdout/stderr:     return self.rename()
23:49:22                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1733, in rename
23:49:22                weechat     | python: stdout/stderr:     new_name = self.formatted_name(style="sidebar", present=self.team.is_user_present(self.user), enable_color=config.colorize_private_chats)
23:49:22                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1108, in is_user_present
23:49:22                weechat     | python: stdout/stderr:     if user.presence == 'active':
23:49:22                weechat     | python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'presence'
23:49:22                weechat =!= | python: error in function "buffer_list_update_callback"
23:49:23                weechat     | python: stdout/stderr: Traceback (most recent call last):
23:49:23                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 126, in wrapper
23:49:23                weechat     | python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
23:49:23                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 741, in buffer_list_update_callback
23:49:23                weechat     | python: stdout/stderr:     b[1].refresh()
23:49:23                weechat     | python: stdout/stderr:   File "/home/dexter/.weechat/python/autoload/wee_slack.py", line 1741, in refresh
23:49:23                weechat     | python: stdout/stderr:     return self.rename()
....
and it keeps going like this...
```

**Comment by d3xt3r01** [comment]
But it seems to work at least ! Great work !

**Comment by trygveaa** [comment]
This should be fixed now. Please comment if you still have any issues.
