### ISSUE TITLE
/join|create or /slack slash /join|/open doesn't create new channels

### ISSUE THREAD

**Issue by moritzheiber** [wee-slack/wee-slack#415]
I might be doing something wrong, but for me with the latest version available from master neither `/join <channel>` nor `/slack slash create <channel>` are working as I would expect them to.

If I wanted to create a new channel I would expect just to be able to run

```
/join #my-channel
```
or
```
/join my-channel
```

However, neither of these commands yields either an output on the server buffer nor does it actually open a new channel. I'm running them from another channel on the same Slack account.

**Comment by trygveaa** [comment]
> `/slack slash create <channel>`

Commands used with `/slack slash` needs to be prefixed with `/`, so this would need to be `/slack slash /create <channel>` to be a valid command. Though, as far as I can see, `/create` isn't an existing command in Slack and it doesn't work in the web client, so I'm not sure why this should work?

> `/join #my-channel`

Since this creates a channel (if it doesn't exist) when used in IRC, it might be logical that it does so in wee-slack as well. However as far as I can see from the code, this isn't implemented. It only tries to join existing channels.

**Comment by moritzheiber** [comment]
I looked it up, and it should be either `open` or `join` (which is an alias for `open`) which either creates or joins a channel. Both of which are not working. I adjusted the title of this issue accordingly.

**Comment by k4k** [comment]
Here's the error I receive when attempting to run `/slack slash /open <room_name>`. I'm running wee-chat.py from HEAD on weechat 1.9.1:

```
python: error in function "slack_command_cb"                                                                                                                                                                                                                                                                                                                                 python: stdout/stderr: Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                    python: stdout/stderr:   File "/Users/twood/.weechat/python/autoload/wee-slack.py", line 105, in wrapper                                                                                                                                                                                                                                                                    python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))                                                                                                                                                                                                                                                                                     python: stdout/stderr:   File "/Users/twood/.weechat/python/autoload/wee-slack.py", line 3043, in slack_command_cb                                                                                                                                                                                                                                                           python: stdout/stderr:     EVENTROUTER.cmds[function_name]("", current_buffer, args)                                                                                                                                                                                                                                                                                         python: stdout/stderr:   File "/Users/twood/.weechat/python/autoload/wee-slack.py", line 94, in wrapper                                                                                                                                                                                                                                                                      python: stdout/stderr:     return f(data, current_buffer, *args, **kwargs)                                                                                                                                                                                                                                                                                                   python: stdout/stderr:   File "/Users/twood/.weechat/python/autoload/wee-slack.py", line 3084, in command_slash                                                                                                                                                                                                                                                              python: stdout/stderr:     s = SlackRequest(team.token, "chat.command", {"command": command, "text": text, 'channel': channel.identifier}, team_hash=team.team_hash, channel_identifier=channel.identifier)                                                                                                                                                                  python: stdout/stderr: AttributeError: 'SlackTeam' object has no attribute 'identifier'                                                                                                                                                                                                                                                                                      python: error in function "slack_command_cb"
```

**Comment by trygveaa** [comment]
Now you can create a channel with `/slack create <channel_name>`.

I chose to not have `/join` automatically create a channel, because Slack differs from IRC in that in IRC the channel will be gone if you leave it again, but with Slack it will remain unless you delete it. Therefore I didn't see automatically creating one with `/join` as a good idea.

Currently the channel buffer isn't switched to automatically after it has been created, even if `switch_buffer_on_join` is set to true. That is a todo for later.
