### ISSUE TITLE
python: error in function "command_talk"

### ISSUE THREAD

**Issue by brandon-arnold** [wee-slack/wee-slack#433]
Hi,

I've just installed the 1.0 RC1 version of wee-slack. I'm using Python 2.7.13 and WeeChat 1.6. I set my landdox team's key and it successfully authenticates on startup. But if I `/join #channel-name` from the team buffer, I get the following error:

```
11:29:40           weechat     | python: stdout/stderr: Traceback (most recent call last):                                                          │
11:29:40           weechat     | python: stdout/stderr:   File "/home/brandon/.weechat/python/autoload/wee_slack.py", line 81, in wrapper           │
11:29:40           weechat     | python: stdout/stderr:     return f(data, current_buffer, *args, **kwargs)                                         │
11:29:40           weechat     | python: stdout/stderr:   File "/home/brandon/.weechat/python/autoload/wee_slack.py", line 2573, in command_talk    │
11:29:40           weechat     | python: stdout/stderr:     channel_name = arg[1:]                                                                  │
11:29:40           weechat     | python: stdout/stderr: NameError: global name 'arg' is not defined                                                 │
11:29:40           weechat =!= | python: error in function "command_talk"                                                                           │
```

Any ideas?

-Brandon

**Comment by brandon-arnold** [comment]
Looks like an error on that line in `wee_slack.py`. `arg[1:]` should be `args[1:]`.

**Comment by trygveaa** [comment]
The code in master doesn't have this line. Can you try updating to the newest version?

**Comment by trygveaa** [comment]
Closing as I don't think this is a problem anymore, and I didn't get a response. Please reopen with more info or open a new issue if this is still a problem.
