### ISSUE TITLE
Unable to delete nth message

### ISSUE THREAD

**Issue by k4k** [wee-slack/wee-slack#469]
Using `3s///` produces the following error:

```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/Users/twood/.weechat/python/autoload/wee-slack.py", line 112, in wrapper
python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
python: stdout/stderr:   File "/Users/twood/.weechat/python/autoload/wee-slack.py", line 665, in buffer_input_callback
python: stdout/stderr:     channel.edit_nth_previous_message(msgno, old, new, flags)
python: stdout/stderr:   File "/Users/twood/.weechat/python/autoload/wee-slack.py", line 1400, in edit_nth_previous_message
python: stdout/stderr:     s = SlackRequest(self.team.token, "chat.delete", {"channel": self.identifier, "ts": message['ts']}, team_hash=self.team.team_hash, channel_identifier=self.identifier)
python: stdout/stderr: TypeError: 'NoneType' object has no attribute '__getitem__'
python: error in function "buffer_input_callback"
```

**Comment by trygveaa** [comment]
This works for me now at least. Please reopen if you still experience this issue.
