### ISSUE TITLE
newest wee-slack broken after new user added to org

### ISSUE THREAD

**Issue by ryansyah** [wee-slack/wee-slack#482]
Hello,

I've been a daily user of wee-slack now for a little over a year. My configuration broke this last weekend on the most recent RC code in what appears to me as user mixup/identification issue.

Fun side note, my name is Ryan Stark and another Ryan Stark was added to our org over the last couple of weeks.

Here is a debug output sample from a fresh weechat-1.9.1 on FreeBSD-11.1, using weechat-1.0-RC1 (says 1.99 internally):

```
python scripts loaded: slack
Plugins loaded: alias, aspell, buflist, charset, exec, fifo, irc, logger, lua, perl, python, relay, ruby, script, tcl, trigger, xfer
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 502, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 490, in handle_next
python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 2104, in handle_rtmstart
python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 1596, in __init__
python: stdout/stderr:     kwargs["name"] = users[dmuser].name
python: stdout/stderr: KeyError: u'U03XXXXXX'
```

My Slack Community member ID is: U0CYYYYYY
The 'new' Ryan Stark Slack Community member ID is: U03XXXXXX

I should also note that when I revert to 0.99.11 code,  the plugin does function although it has it's own errors reported:
```
slack: DEBUG: Loading messages from cache.
slack: DEBUG: Completed loading messages from cache.
python scripts loaded: slack_extension
Plugins loaded: alias, aspell, buflist, charset, exec, fifo, irc, logger, lua, perl, python, relay, ruby, script, tcl, trigger, xfer
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/usr/home/foo/.weechat/python/autoload/wee_slack.py", line 2316, in url_processor_cb
python: stdout/stderr:     servers.find(data["token"]).connected_to_slack(my_json)
python: stdout/stderr:   File "/usr/home/foo/.weechat/python/autoload/wee_slack.py", line 266, in connected_to_slack 
python: stdout/stderr:     self.create_slack_mappings(login_data)
python: stdout/stderr:   File "/usr/home/foo/.weechat/python/autoload/wee_slack.py", line 340, in create_slack_mappings
python: stdout/stderr:     self.add_channel(Channel(self, **item))
python: stdout/stderr:   File "/usr/home/foo/.weechat/python/autoload/wee_slack.py", line 190, in add_channel
python: stdout/stderr:     self.channels.append(channel, channel.get_aliases())
python: stdout/stderr:   File "/usr/home/foo/.weechat/python/autoload/wee_slack.py", line 472, in get_aliases
python: stdout/stderr:     aliases = [self.fullname(), self.name, self.identifier, self.name[1:], ]
python: stdout/stderr:   File "/usr/home/foo/.weechat/python/autoload/wee_slack.py", line 554, in fullname
python: stdout/stderr:     return "{}.{}".format(self.server.server_buffer_name, self.name)
python: stdout/stderr: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 5: ordinal not in range(128)
python: error in function "url_processor_cb"
Disconnected from slack, trying to reconnect..
.
.
.
Connected to Slack
Websocket URL        wss://XXXXXXXXXXXXXXX
User name           XXXXXX
User ID
Team name 
Team domain
Team id
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 1558, in slack_websocket_cb
python: stdout/stderr:     proc[function_name](message_json)
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 1746, in process_im_marked 
python: stdout/stderr:     channel.mark_read(False)
python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'mark_read'
python: error in function "slack_websocket_cb"
.
.
.
```

**Comment by ryansyah** [comment]
related?

https://api.slack.com/changelog/2017-09-the-one-about-usernames

**Comment by ToxicFrog** [comment]
Possibly. I have a local branch I need to make a PR from that uses display_name in place of username, since username is no longer trustworthy, but I don't think it's fully baked yet.

**Comment by ryansyah** [comment]
I was able to upgrade to weechat 2.0 today so repeated my testing and found the same results using the newest wee-slack plugin.

```
WeeChat 2.0 [compiled on Dec  5 2017 13:11:57]
python scripts loaded: slack
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 502, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 490, in handle_next
python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 2104, in handle_rtmstart
python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 1596, in __init__
python: stdout/stderr:     kwargs["name"] = users[dmuser].name
python: stdout/stderr: KeyError: u'U03XXXXXX'

**Comment by trygveaa** [comment]
Do you have a shared channel, or a dm with a person from another team?

**Comment by ryansyah** [comment]
@trygveaa , I have joined a shared channel and had a single DM with a person from another team (My doppelganger). At the time I had done these two things (early last week), wee-slack was working fine. It was not until a after workstation reboot Thursday that I noticed the plugin issue reported here the following workday, Friday.

When submitting this issue yesterday after troubleshooting and again today, I did not have any DM's open with members from other teams, nor do I have any shared channels open in my slack webclient.

Another fun tidbit. When searching for the 'Ryan Stark' in the slack webclient last week, I did not initially get results from members on other teams. Only after joining a shared channel and then re-doing a search for 'Ryan Stark' did I get any results from other teams, which then allowed me to open a DM with the other team member of the same name. 

Fast forward to today, with no open DM's or shared channels joined, my slack webclient regularly returns results for both 'Ryan Stark' users. Further, when I have another slack user on my team perform the same search 'Ryan Stark' test from their webclient that has never joined said shared channel or had an DM's with members from other teams, they only see only one Ryan Stark result, and not results for both teams... This behavior seems to indicate that slack may be 'caching' information from previous DM's, which *may* be impacting my issue?

**Comment by trygveaa** [comment]
Hm, okay.

> This behavior seems to indicate that slack may be 'caching' information from previous DM's, which may be impacting my issue?

Yes, when you query slack for the list of dms, it includes previous dms, which has been closed.

This seems like the same error as https://github.com/wee-slack/wee-slack/issues/454, at least the KeyError, not sure about the other ones.

Could you try PR https://github.com/wee-slack/wee-slack/pull/462?

**Comment by ryansyah** [comment]
@trygveaa ,

I was able to try PR #462, but the errors I see still looks the same:

```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 510, in handle_next
python: stdout/stderr:     EVENTROUTER.handle_next()
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 498, in handle_next
python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 2153, in handle_rtmstart
python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
python: stdout/stderr:   File "/usr/home/syah/.weechat/python/autoload/wee_slack.py", line 1621, in __init__
python: stdout/stderr:     kwargs["name"] = users[dmuser].name
python: stdout/stderr: KeyError: u'U03XXXXXX'
```

**Comment by ryansyah** [comment]
In a separate thread, I reached out to Slack support yesterday and was able to get a dev to peak at this issue and a chat log with slack support. I'll add some of his email here for review and feedback:

> I had a look at this issue and the discussion at https://github.com/wee-slack/wee-slack/issues/482 and it looks like this could indeed be due to the fact that you now have two users that your auth can "see" with the same name, which probably wasn't expected when wee-slack was coded.
> This being said, could you share more details regarding what you mean here:
"when I try to use a legacy API token to authenticate to my company's slack workspace that is using a BETA feature, I get a return value for member ID that should not be exposed due to it being from another company's slack workspace. "
Do you know which underlying API method is being called to return this value? As you share some channels and a DM with your doppelganger, it is expected that this user will be returned by some methods, but I'd like to make sure that it's not returned for instance when calling https://api.slack.com/methods/users.info with your user_id, which would sound like a bug on our end.

I would be happy to relay information back to the Slack devs, but I lack the insight at this time to provide him a good answer.

**Comment by ryansyah** [comment]
from #wee-slack: ttps://api.slack.com/methods/rtm.start

**Comment by trygveaa** [comment]
To elaborate, when wee-slack starts it calls `rtm.start` and creates users, teams etc. from the response of that. The object storing the users for each team is never changed after that. As far as I know, users from other teams are not included in the user list from `rtm.start`, even if there are channels/IMs with users from other teams. However, the IDs are referenced in such channels/ims. That causes the `KeyError` you pasted.

I think we need to lookup those IDs when initializing the shared channels/IMs to get info about the user, and store it in the users object. I thought #462 did that, but apparently not since you still get the error. I haven't had the time to look at that PR yet unfortunately. It might be that it only does it for shared channels, and not for shared IMs.

**Comment by ryansyah** [comment]
Further feedback from slack folks:

> Hi there,
> Thanks for this additional info!
> This does look like a possible explanation for the error you're seeing. However, what I'm not sure about is whether this is related to the other team having a user with the same name.
> If this issue is due to shared channels only, this doesn't explain why wee-slack is trying to associate you with this other user, so I'm wondering if there could be a reference to the user made via its name rather than its user_id. As usernames are not uniques in the context of shared channels, this could maybe explain this issue.

> I'm not sure if the above makes sense given wee-slack's implementation, as I'm not familiar with the way this is done, but I thought I'd mention this it case it helped explain the issue with your doppelganger.

> Let me know if you have more questions!

**Comment by ryansyah** [comment]
I got asked about this bug by a co-worker today, so spent a few cycles setting up wee-slack on a new laptop. It appears that patch provided in #492 does get me up and running again!
[Avoid error on DM buffer with unknown user
](https://github.com/wee-slack/wee-slack/pull/492/commits/89991da36fd1148e7cf9e4ec286759a6111d0152
)


```
--- wee_slack.py	2018-03-12 09:38:00.000000000 -0500
+++ .weechat/python/autoload/wee_slack.py	2018-03-12 11:24:39.000000000 -0500
@@ -2153,7 +2153,8 @@
             channels[item["id"]] = SlackChannel(eventrouter, **item)

         for item in login_data["ims"]:
-            channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
+            if item["user"] in users:
+                channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)

         for item in login_data["groups"]:
             if item["name"].startswith('mpdm-'):
```

Thanks @rarbab!

**Comment by ryansyah** [comment]
So, while now the plugin loads and functionally operates, I am no longer able to see user lists in public channels, only locked channels. :/

**Comment by tonyskapunk** [comment]
I had similar issues as commented in #462, I tested #492 and I'm able to login, no more issues with DM of persons in shared channels.

I'm experiencing something similar @ryansyah  Some channels have fewer users than it has(including online/away) Examples:
- channel1 shows 6/9 users (it shows some users in away status and some others in active mode, missing both away/active users)
- channel2 shows 8/29 (same as above)
- channel3 shows 2/45

All of them at least show my user in there.

**Comment by trygveaa** [comment]
@ryansyah, @tonyskapunk: The original error should be fixed now. I'm not sure about the error with user lists. Can you test the latest master and check if it's still an issue?

**Comment by ryansyah** [comment]
So, I had a chance to test the current master branch on both my workstation and laptop. The code looks to be working fine for me with a caveat below.

One thing I can comment on, I sit in about 60 slack channels, some of them have hundreds of members (#general), many are fairly high traffic. On my workstation, weechat is always running and wee-slack is always connected to slack. This machine worked straight away with the new wee-slack plugin with no observable issues on any channel. (.weechat on this computer is ~200MB). However, when I tried the same testing on my laptop which I rarely use weechat on (.weechat = 7MB), I noticed it took a long time for some channels to get past `getting channel history...` and to fully populate user lists, even an hour later. I am not sure if this is another bug, but wanted to bring it up. The channel is 'functional' for new messages and general interactions, but the history and userlists are slow to populate. I can say that user lists for private slack channels seem to populate quickly and before any public slack channels have populated userlists. The only non-private slack channel I am on with a sub-set of the full userlist populated is #general. My laptop client currently lists around 350 users, but the native slack client shows that this channel with 7,144 users. I am going to see if 'just letting it run' will eventually fix my history and userlist discrepancies and report back with my findings.

**Comment by ryansyah** [comment]
While there are still issues with one of my wee-slack instances and history as described above,  the original issue reported here does now appear to be resolved.

Thank you!
