### ISSUE TITLE
Failed to login with command `/slack register [code]`

### ISSUE THREAD

**Issue by jackalcooper** [wee-slack/wee-slack#517]
Here is the log:
```
         │14:49:04     | python: stdout/stderr: Traceback (most recent call last):
         │14:49:04     | python: stdout/stderr:   File "/Users/jackalcooper/.weechat/python/autoload/wee_slack.py", line 115, in wrapper
         │14:49:04     | python: stdout/stderr:     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
         │14:49:04     | python: stdout/stderr:   File "/Users/jackalcooper/.weechat/python/autoload/wee_slack.py", line 3238, in slack_command_cb
         │14:49:04     | python: stdout/stderr:     EVENTROUTER.cmds[function_name]("", current_buffer, args)
         │14:49:04     | python: stdout/stderr:   File "/Users/jackalcooper/.weechat/python/autoload/wee_slack.py", line 3053, in command_register
         │14:49:04     | python: stdout/stderr:     d = json.loads(ret)
         │14:49:04     | python: stdout/stderr:   File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
         │14:49:04     | python: stdout/stderr:     return _default_decoder.decode(s)
         │14:49:04     | python: stdout/stderr:   File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
         │14:49:04     | python: stdout/stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
         │14:49:04     | python: stdout/stderr:   File "/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
         │14:49:04     | python: stdout/stderr:     raise ValueError("No JSON object could be decoded")
         │14:49:04     | python: stdout/stderr: ValueError: No JSON object could be decoded
         │14:49:04 =!= | python: error in function "slack_command_cb"
```

**Comment by ryansyah** [comment]
I configured weechat + wee-slack on a new laptop today, using the `/slack register` method for the first time. I was unable to connect to slack after a `/python reload` and a weechat client restart. I had previously configured a legacy API token for use, reissued a new legacy token today via the slack webpage and added the token to weechat via `/set plugins.var.python.slack.slack_api_token [YOUR_SLACK_TOKEN]` && weechat client restart worked as expected, wee-slack plugin loaded fine.

**Comment by trygveaa** [comment]
The error handling for that command is better now (after PR #582), so I think this is fixed. Please comment or reopen if it's still an issue.
