### ISSUE TITLE
can't register when behind a proxy

### ISSUE THREAD

**Issue by Coolgeek789** [wee-slack/wee-slack#573]
I can't register when behind a proxy. error : 
```
 python : stdout/stderr (slack) : Traceback (most recent call last):
 python : stdout/stderr (slack) :   File "/home/frendu/.weechat/python/autoload/wee_slack.py", line 119, in wrapper
 python : stdout/stderr (slack) :     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
 python : stdout/stderr (slack) :   File "/home/frendu/.weechat/python/autoload/wee_slack.py", line 3282, in slack_command_cb
 python : stdout/stderr (slack) :     EVENTROUTER.cmds[function_name]("", current_buffer, args)
 python : stdout/stderr (slack) :   File "/home/frendu/.weechat/python/autoload/wee_slack.py", line 3097, in command_register
 python : stdout/stderr (slack) :     d = json.loads(ret)
 python : stdout/stderr (slack) :   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
 python : stdout/stderr (slack) :     return _default_decoder.decode(s)
 python : stdout/stderr (slack) :   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
 python : stdout/stderr (slack) :     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 python : stdout/stderr (slack) :   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
 python : stdout/stderr (slack) :     raise ValueError("No JSON object could be decoded")
 python : stdout/stderr (slack) : ValueError: No JSON object could be decoded
```

After tracking down, I changed the line "ret = urllib.urlopen(uri).read()" by "ret = urllib2.urlopen(uri).read()" in function command_register.

It works now. It use http_proxy/https_proxy env var to lookup the proxy address. Maybe it should use the proxy system given by weechat.

**Comment by yardenac** [comment]
Thanks. Maybe this should be a pull request

**Comment by Coolgeek789** [comment]
I'm no python dev, but I can try to make something. I'm not sure how much time it will take though.
I'm sure you can make something much faster than me. And much cleaner too

**Comment by trygveaa** [comment]
We should probably use `w.hook_process_hashtable` to request the url instead of urllib, like we do in `local_process_async_slack_api_request`. This will make weechat perform the request, so it should use the proxy settings automatically.
