### ISSUE TITLE
ProcessNotImplemented: channelsmark / ProcessNotImplemented: immark

### ISSUE THREAD

**Issue by timdau** [wee-slack/wee-slack#588]
Immediately after I send a msg in a channel, this is what I get.  Also, channels aren't being updated.

`12:07:22          weechat     | python: stdout/stderr (slack): WS ERROR`
`12:07:24          weechat     | python: stdout/stderr (slack): Traceback (most recent call last):`
`12:07:24          weechat     | python: stdout/stderr (slack):   File "/home/paul/.weechat/python/autoload/wee_slack.py", line 509, in handle_next`
`12:07:24          weechat     | python: stdout/stderr (slack):     EVENTROUTER.handle_next()`
`12:07:24          weechat     | python: stdout/stderr (slack):   File "/home/paul/.weechat/python/autoload/wee_slack.py", line 499, in handle_next`
`12:07:24          weechat     | python: stdout/stderr (slack):     raise ProcessNotImplemented(function_name)`
`12:07:24          weechat     | python: stdout/stderr (slack): ProcessNotImplemented: channelsmark`

If I send a DM I get the same except:

`12:17:56          weechat     | python: stdout/stderr (slack): ProcessNotImplemented: immark`

Versions:
weechat 2.1
wee-slack cd6f687 ( 10 days ago )

Steps to reproduce:
rm -rf ~/.weechat
weechat (to generate basic cfg)
/quit
wget -O ~/.weechat/python/autoload/wee_slack.py https://raw.githubusercontent.com/wee-slack/wee-slack/master/wee_slack.py
weechat
/set plugins.var.python.slack.slack_api_token $TOKEN
/set plugins.var.python.slack.debug_level 2
/set plugins.var.python.slack.debug_mode on
/save
/python reload slack
enter a msg in a channel or DM

**Comment by timdau** [comment]
I upgraded from wheezy to jessie and its working now.
