### ISSUE TITLE
UnicodeDecodeError when the connection fails

### ISSUE THREAD

**Issue by brunobord** [wee-slack/wee-slack#593]
For some reasons, I'm regularly disconnected from the Slack API (I'd say 10 times per day on average). I don't know the root cause of this problem, and I may investigate a bit later, but it raised another issue with the `dbg` function.

Traceback:

```
10:28:43             weechat     | python : stdout/stderr : Traceback (most recent call last):
10:28:43             weechat     | python : stdout/stderr :   File "/home/username/.weechat-slack/python/autoload/wee_slack.py", line 119, in wrapper
10:28:43             weechat     | python : stdout/stderr :     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
10:28:43             weechat     | python : stdout/stderr :   File "/home/username/.weechat-slack/python/autoload/wee_slack.py", line 658, in receive_ws_callback
10:28:43             weechat     | python : stdout/stderr :     EVENTROUTER.receive_ws_callback(args[0])
10:28:43             weechat     | python : stdout/stderr :   File "/home/username/.weechat-slack/python/autoload/wee_slack.py", line 391, in receive_ws_callback
10:28:43             weechat     | python : stdout/stderr :     dbg("socket issue: {}\n".format(traceback.format_exc()))
10:28:43             weechat     | python : stdout/stderr : UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1115: ordinal not in range(128)
10:28:43             weechat =!= | python : erreur dans la fonction "receive_ws_callback"
```

Looks like some characters in the `traceback.format_exc()` are not correctly formatted.
I've changed the lines to:

```python
        except Exception as exc:
            print(exc)
            return w.WEECHAT_RC_OK
```

here's the output:

```
10:51:09             weechat     | python : stdout/stderr : [Errno 110] Connexion terminée par expiration du délai d'attente
```

there are accentuated characters, because for some unknown reason, the error is translated in French. I guess that this call to `dbg` has to be safely re-encoded.

Do you think it could be solved by using `(de|en)code_from_utf8`?

**Comment by brunobord** [comment]
FYI, the error means there's a timeout.
