### ISSUE TITLE
Can not send messages

### ISSUE THREAD

**Issue by kthibodeaux** [wee-slack/wee-slack#662]
I can not send messages.  I tried updating to the latest weeslack but that did not seem to help.

Initially it seemed I could not receive them either, but it seems that is not the issue I thought it was.

Any ideas?

Edit, I found in another issue how to enable debug output, here is what I get when I try to send a message:

```
                        │08:55:11                   weechat     | python: stdout/stderr: Traceback (most recent call last):
                        │08:55:11                   weechat     | python: stdout/stderr:   File "/home/kthibodeaux/.weechat/python/autoload/wee_slack.py", line 574, in
                        │                                       | handle_next
                        │08:55:11                   weechat     | python: stdout/stderr:     EVENTROUTER.handle_next()
                        │08:55:11                   weechat     | python: stdout/stderr:   File "/home/kthibodeaux/.weechat/python/autoload/wee_slack.py", line 560, in
                        │                                       | handle_next
                        │08:55:11                   weechat     | python: stdout/stderr:     self.proc[function_name](j, self, **kwargs)
                        │08:55:11                   weechat     | python: stdout/stderr:   File "/home/kthibodeaux/.weechat/python/autoload/wee_slack.py", line 2742, in
                        │                                       | process_reply
                        │08:55:11                   weechat     | python: stdout/stderr:     channel=channel, team=team)
                        │08:55:11                   weechat     | python: stdout/stderr:   File "/home/kthibodeaux/.weechat/python/autoload/wee_slack.py", line 2617, in
                        │                                       | process_message
                        │08:55:11                   weechat     | python: stdout/stderr:     if SlackTS(message_json["ts"]) in channel.messages:
                        │08:55:11                   weechat     | python: stdout/stderr: KeyError: u'ts'
```

**Comment by kthibodeaux** [comment]
This appears to be fixed.  I didn't change anything, so maybe this was a Slack issue?

**Comment by trygveaa** [comment]
Hm, the traceback indicates that the api-response after sending a message is missing the ts-field. Maybe there are some messages we don't handle properly?

It would be interesting to see the contents of `message_json` there, but if it doesn't happen anymore, that might be hard.

**Comment by kthibodeaux** [comment]
The message I sent to get the error was `test`.  I can send it now without issues.

¯\_(ツ)_/¯
