### ISSUE TITLE
AttributeError: 'SlackTeam' object has no attribute 'hashed_messages'

### ISSUE THREAD

**Issue by letalvoj** [wee-slack/wee-slack#737]
Fresh install

- MacOS: `10.14.6 (18G103)`
- Python: `3.7.5`
- Command: `/thread general`
- Result:
```
weechat     | python: stdout/stderr (slack): Traceback (most recent call last):
weechat     | python: stdout/stderr (slack):   File "/Users/vojta/.weechat/python/autoload/wee_slack.py", line 145, in wrapper
weechat     | python: stdout/stderr (slack):     return f(data, current_buffer, *args, **kwargs)
weechat     | python: stdout/stderr (slack):   File "/Users/vojta/.weechat/python/autoload/wee_slack.py", line 156, in wrapper
weechat     | python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
weechat     | python: stdout/stderr (slack):   File "/Users/vojta/.weechat/python/autoload/wee_slack.py", line 4036, in command_thread
weechat     | python: stdout/stderr (slack):     msg = get_msg_from_id(channel, args)
weechat     | python: stdout/stderr (slack):   File "/Users/vojta/.weechat/python/autoload/wee_slack.py", line 4022, in get_msg_from_id
weechat     | python: stdout/stderr (slack):     return channel.hashed_messages.get(msg_id)
weechat     | python: stdout/stderr (slack): AttributeError: 'SlackTeam' object has no attribute 'hashed_messages'
weechat =!= | python: error in function "command_thread"
```

**Comment by trygveaa** [comment]
This should give a better error message, but the error is that your're trying to use the `/thread` command in the team buffer. It should only be used in channel buffers. Additionally, the argument you should give to it is a thread id, not a channel name.
