### ISSUE TITLE
Usage of `rtm.start` may break in September

### ISSUE THREAD

**Issue by episod** [wee-slack/wee-slack#866]
Hello from Slack developer relations.

It looks like you're still using the `rtm.start` method to negotiate websocket URLs for connecting to the RTM API. On September 20, 2022 the response to `rtm.start` will change to that of `rtm.connect` -- without all the extra info about channels, users, and the workspace you've come to expect from `rtm.start`. You may want to get ahead of that date and verify you can still connect and use the Web API to retrieve current state information instead.

There will be a short preview of this behavior on September 13, 2022 but you can test it out today. More info about this deprecation announced back in October 2021 can be found here: https://api.slack.com/changelog/2021-10-rtm-start-to-stop

**Comment by michaeljoelphillips** [comment]
I suspect that I have encountered issues with the changes described above, as connecting via `wee-slack` prior to today (September 13th, 2022) was working.

```
Option changed: plugins.var.python.slack.debug_mode = "on"
Option changed: plugins.var.python.slack.debug_level = "5"
python: unloading script "slack"
python: script "slack" unloaded
python: loading script "/home/nomad/.weechat/python/autoload/wee_slack.py"
python: registered script "slack", version 2.8.0 (Extends weechat for typing notification/search/etc on slack.com)
Connecting to 4 slack teams.
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 843, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 836, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, team, channel, metadata)
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 3582, in handle_rtmstart
python: stdout/stderr (slack):     for user in login_data["users"]
python: stdout/stderr (slack): KeyError: 'users'
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 843, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 836, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, team, channel, metadata)
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 3582, in handle_rtmstart
python: stdout/stderr (slack):     for user in login_data["users"]
python: stdout/stderr (slack): KeyError: 'users'
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 843, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 836, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, team, channel, metadata)
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 3582, in handle_rtmstart
python: stdout/stderr (slack):     for user in login_data["users"]
python: stdout/stderr (slack): KeyError: 'users'
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 843, in handle_next
python: stdout/stderr (slack):     EVENTROUTER.handle_next()
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 836, in handle_next
python: stdout/stderr (slack):     self.handlers[function_name](j, self, team, channel, metadata)
python: stdout/stderr (slack):   File "/home/nomad/.weechat/python/autoload/wee_slack.py", line 3582, in handle_rtmstart
python: stdout/stderr (slack):     for user in login_data["users"]
python: stdout/stderr (slack): KeyError: 'users'
```

**Comment by dlbeer** [comment]
If it helps, the response to `rtmstart` now looks like this:

```
{
    "ok": true,
    "response_metadata": {
        "messages": [
            "[WARN] method_deprecated: Please use rtm.connect to connect to the RTM API instead. Learn more at https://api.slack.com/changelog/2021-10-rtm-start-to-stop"
        ]
    },
    "self": {
        "id": "Uredacted",
        "name": "daniel.beer"
    },
    "team": {
        "domain": "redacted",
        "id": "Tredacted",
        "name": "Human-Readable Redacted"
    },
    "url": "wss://wss-primary.slack.com/websocket/C-redacted",
    "wee_slack_process_method": "rtmstart"
}
```

It looks like another couple of API calls are required to get the channel and user lists. I'm happy to test/debug anything.

**Comment by michaeljoelphillips** [comment]
Now that the preview for the changes to `rtm.start` has ended, `wee-slack` is working.  Unless patched, we can expect `wee-slack` to be broken again after September 20th.

**Comment by nipsy** [comment]
Just to say, I was bitten by this also.  It looks like https://github.com/wee-slack/wee-slack/pull/857 includes the necessary bits to fix this already potentially.

**Comment by trygveaa** [comment]
Sorry for the delay here and that I missed the preview period, and thanks for the heads up @episod!

@nipsy: You are indeed correct that #857 has fixed this by replacing the usage of `rtm.start` with other API methods. I'll try to get it merged and make a new release before Tuesday.

**Comment by trygveaa** [comment]
This has now been fixed with the 2.9.0 release.

**Comment by trygveaa** [comment]
Ah, yes, thanks. I unpinned it now.
