### ISSUE TITLE
error in function command_reply - IndexError: list index out of range

### ISSUE THREAD

**Issue by kucharskim** [wee-slack/wee-slack#900]
I just did `/reply` without any arguments and I think this is how below happened:
```
python: stdout/stderr (slack): Traceback (most recent call last):
python: stdout/stderr (slack):   File "/home/username/.local/share/weechat/python/autoload/wee_slack.py", line 174, in wrapper
python: stdout/stderr (slack):     return f(data, current_buffer, *args, **kwargs)
python: stdout/stderr (slack):   File "/home/username/.local/share/weechat/python/autoload/wee_slack.py", line 187, in wrapper
python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
python: stdout/stderr (slack):   File "/home/username/.local/share/weechat/python/autoload/wee_slack.py", line 5795, in command_reply
python: stdout/stderr (slack):     if parts[0] == "-alsochannel":
python: stdout/stderr (slack): IndexError: list index out of range
python: error in function "command_reply"
```

**Comment by kucharskim** [comment]
This is happening on 5302c8701c5411c28a00b022600ee7cd723718e2 version.

**Comment by kucharskim** [comment]
Gonna upgrade to 24439521d1147a2b5700a6cea0aea310c5dccb61 and see how it goes.
