### ISSUE TITLE
rehistory error on slack call

### ISSUE THREAD

**Issue by grassdionera** [wee-slack/wee-slack#904]
When i do /rehistory command on a specific private channel i got the following error

```
08:10 python: stdout/stderr: (slack): Traceback (most recent call last):
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 174, in wrapper
08:10 python: stdout/stderr: (slack):     return f(data, current_buffer, *args, **kwargs)
08:10 python: stdout/stderr: (slack):            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 187, in wrapper
08:10 python: stdout/stderr: (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
08:10 python: stdout/stderr: (slack):            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 5845, in command_rehistory
08:10 python: stdout/stderr: (slack):     channel.reprint_messages(force_render=True)
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 1971, in reprint_messages
08:10 python: stdout/stderr: (slack):     self.prnt_message(message, history_message, no_log, force_render)
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 1909, in prnt_message
08:10 python: stdout/stderr: (slack):     text = self.render(message, force_render)
08:10 python: stdout/stderr: (slack):            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 2779, in render
08:10 python: stdout/stderr: (slack):     text = message.render(force)
08:10 python: stdout/stderr: (slack):            ^^^^^^^^^^^^^^^^^^^^^
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 3431, in render
08:10 python: stdout/stderr: (slack):     text += unfurl_refs(unwrap_huddle(self, self.message_json))
08:10 python: stdout/stderr: (slack):                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08:10 python: stdout/stderr: (slack):   File "/home/mg/.local/share/weechat/python/autoload/wee_slack.py", line 4819, in unwrap_huddle
08:10 python: stdout/stderr: (slack):     for block in message_json.get("blocks"):
08:10 python: stdout/stderr: (slack): TypeError: 'NoneType' object is not iterable
08:10 =!= python: Fehler in Funktion "command_rehistory"
```

in the private channel i can see all messages until one message that is a Missed Slack Call. 
with that message wee_slack is not loading any further messages for this channel

**Comment by grassdionera** [comment]
problem is solved with newest version 2.10.1 
sorry
