### ISSUE TITLE
ERROR: Failed connecting to Slack with token ...: channels: enterprise_is_restricted

### ISSUE THREAD

**Issue by yazgoo** [wee-slack/wee-slack#910]
```
ERROR: Failed connecting to Slack with token <...>: channels: enterprise_is_restricted, presence: enterprise_is_restricted, channels: enterprise_is_restricted
```

Seems the same as

https://github.com/yuya373/emacs-slack/issues/543

**Comment by trygveaa** [comment]
What kind of token do you use? (Which four characters does it start with)

**Comment by github-olivier-abdesselam** [comment]
I have

```
python.slack.slack_api_token = xoxc-.....:xoxd-....
```

The error is:

```
ERROR: Failed connecting to Slack with token xoxc-<start of xoxc token>...<end of xoxd token>: channels: enterprise_is_restricted, presence: enterprise_is_restricted, channels: enterprise_is_restricted
```

**Comment by yazgoo** [comment]
I have

```
python.slack.slack_api_token = xoxc-.....:xoxd-....
```

The error is:

```
ERROR: Failed connecting to Slack with token xoxc-<start of xoxc token>...<end of xoxd token>: channels: enterprise_is_restricted, presence: enterprise_is_restricted, channels: enterprise_is_restricted
```

**Comment by trygveaa** [comment]
Hm, okay, so the workspace apparently restricts the usage of some API methods. Unfortunately it's impossible for me to know which API methods I can use in this case, and which I could potentially replace them with since I don't have any such restricted workspaces.

**Comment by tokyo-kinney** [comment]
The updated Events API includes authorizations inside the event payload on most events.

{
    "token": "XXYYZZ",
    "is_ext_shared_channel": false,
    "team_id": "TXXXXXXXX",
    "api_app_id": "AXXXXXXXXX",
    "event": {...},
    "type": "event_callback",
    "event_id": "EvXXXXXXXX",
    "event_time": 1234567890,
    "authorizations": [
        {
            "enterprise_id": "E324567",
            "team_id": "T423567",
            "user_id": "W43567",
            "is_bot": false,
            "is_enterprise_install": true
        }
    ]
}
So maybe the team_id also needs to be included?

**Comment by pierg75** [comment]
I had a go at debugging this. From the logs I can see three calls which got `enterprise_is_restricted`:

```
{"ok": false, "error": "enterprise_is_restricted", "wee_slack_process_method": "conversationslist"}

{"ok": false, "error": "enterprise_is_restricted", "wee_slack_process_method": "conversationslist"}

{"ok": false, "error": "enterprise_is_restricted", "wee_slack_process_method": "usersgetPresence"}
```

Would this be from the `initiate_connection()` where we have few calls without the team?
Still trying to figure it out how to get the team at that stage.

**Comment by github-olivier-abdesselam** [comment]
I managed to have it not crash by commenting the code below:

So to summup, the issues come from `conversation.list` and `users.getPresence`

line 7200

```python
#    s = SlackRequest(
#        None,
#        "conversations.list",
#        {
#            "exclude_archived": True,
#            "types": "public_channel,private_channel,im",
#            "limit": 1000,
#        },
#        token=token,
#        callback=handle_initial("channels"),
#    )
#    EVENTROUTER.receive(s)
#    s = SlackRequest(
#        None,
#        "conversations.list",
#        {
#            "exclude_archived": True,
#            "types": "mpim",
#            "limit": 1000,
#        },
#        token=token,
#        callback=handle_initial("channels"),
#    )
#    EVENTROUTER.receive(s)
```

l. 7247

```
#    s = SlackRequest(
#        None,
#        "users.getPresence",
#        token=token,
#        callback=handle_getPresence,
#    )
#    EVENTROUTER.receive(s)
```

**Comment by yazgoo** [comment]
I managed to have it not crash by commenting the code below:

So to summup, the issues come from `conversation.list` and `users.getPresence`

line 7200

```python
#    s = SlackRequest(
#        None,
#        "conversations.list",
#        {
#            "exclude_archived": True,
#            "types": "public_channel,private_channel,im",
#            "limit": 1000,
#        },
#        token=token,
#        callback=handle_initial("channels"),
#    )
#    EVENTROUTER.receive(s)
#    s = SlackRequest(
#        None,
#        "conversations.list",
#        {
#            "exclude_archived": True,
#            "types": "mpim",
#            "limit": 1000,
#        },
#        token=token,
#        callback=handle_initial("channels"),
#    )
#    EVENTROUTER.receive(s)
```

l. 7247

```python
#    s = SlackRequest(
#        None,
#        "users.getPresence",
#        token=token,
#        callback=handle_getPresence,
#    )
#    EVENTROUTER.receive(s)
```

**Comment by yazgoo** [comment]
I got a first version somewhat working

https://github.com/wee-slack/wee-slack/pull/916

**Comment by trygveaa** [comment]
I also worked on this a short while ago as I too started experiencing this problem, but I hadn't pushed it yet as there are still some things remaining. But I pushed it now to the [3.0.0 branch](https://github.com/wee-slack/wee-slack/tree/3.0.0). This branch is a large rewrite and there are still some features missing, but it should be usable.

Note that the `wee_slack.py` file in that branch is not in use anymore. You have to either get the `slack.py` script form the [commit build artifact](https://github.com/wee-slack/wee-slack/actions/runs/7360459593) (this link is to the current latest commit, but if there's been new pushes when you read this you should go to the latest commit), or get the whole repo/directory and load the `main.py` file.

Also, the configuration has been completely changed, and there is no automatic migration yet, so you have to configure it from scratch. There is no documentation yet except on the options themselves (as seen in /fset), but to add a new Slack workspace use `/slack workspace add`. The options in use in this version start with `slack.` (not `plugins.var.python.slack.`).

**Comment by yazgoo** [comment]
excellent news !

**Comment by pierg75** [comment]
I tried to use the new version, but I keep getting `invalid_auth`.
This is what I did:
- Added a workspace
- Added the token `xoxc...`
- Added the cookies `xoxd...`
- Tried to connect
Is there something I forgot or did wrong?

This is the error I got:
```
10:23:08     │ Last error:                                                                                                                                                                                     │
10:23:08     │   5edc4ad0-4e7c-49f1-80cf-cdba23e87189 (2024-01-06 10:18:48.304383): SlackApiError: workspace=SlackWorkspace(XXXXX), method='client.counts', params={}, response={'ok': False, 'error':        │
             │ 'invalid_auth'}                                                                                                                                                                                 │
10:23:08     │   Traceback (most recent call last):                                                                                                                                                            │
10:23:08     │     File "/home/user/.local/share/weechat/python/autoload/slack.py", line 366, in task_runner                                                                                                │
10:23:08     │     future = task.coroutine.send(None)                                                                                                                                                          │
10:23:08     │              ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                          │
10:23:08     │     File "/home/user/.local/share/weechat/python/autoload/slack.py", line 3665, in fetch_client_counts                                                                                       │
10:23:08     │     raise SlackApiError(self.workspace, method, response)                                                                                                                                       │
10:23:08     │   SlackApiError: SlackApiError: workspace=SlackWorkspace(XXXXX), method='client.counts', params={}, response={'ok': False, 'error': 'invalid_auth'}    
```

**Comment by trygveaa** [comment]
@pierg75: This version required you to specify the cookie key in addition to the value, and didn't encode the cookie if it wasn't encoded like the released version does. I pushed some changes to encode it if necessary and use the value as the `d` cookie if no key is specified. So if you pull the latest version and try again it hopefully works now.

**Comment by pierg75** [comment]
Thanks a lot. It works now, I'll give a better test on Monday.
