### ISSUE TITLE
branch 3.0.0 is failing on some channels with 'error': 'too_many_users' after stable faling entirely with channels: internal_error

### ISSUE THREAD

**Issue by nipsy** [wee-slack/wee-slack#924]
This morning I ran into a new problem with the current stable branch where I was getting the following error:

```
ERROR: Failed connecting to Slack with token xoxp-xxxxxxxxxx...xxxxxxxxxx: channels: internal_error
```

I ran across the recommendation in #910 to try out the 3.0.0 development branch, which got me connected and working for the most part.

However, our company has a general channel with every employee in it, which seems to be causing the following error now:

```
2024-03-27 10:44:06     =!=     slack: Error while handling Slack event of type 'user_status_changed' for workspace work: SlackApiError: SlackApiError: workspace=SlackWorkspace(mirantis), method='users.info', request={'users': 'UDPNC2ZPH,U037C7YB5GR,U045SE7K66N,U046HRJHFUY,UC7B7UX5Z,U03MNEDH8,U02FSG14XR8,UCFGX08KV,URFRMCFV4,U05R371HGET,U03ENFT1L,U02R6MVUGPM,U05G6FP22FP,UDTMF9UN8,U01U444H2GY,U015A35BMBJ,U04JAH0GQ,U02U8J440S1,U03N7T87R,U01GLA0FTBR,U03PUSTPC,U03MN1NDQ,U05R36FKS07,U096GR06P,UTL7Q54ES,UQWN6GXGB,UF0TT9JEQ,U04RXGWJL,U05RHN0DTJ6,UEDDVEQV7,UVBUGC1SA,U05S6N1DLLQ,U07DZ8CRM,U04HXTHM6AZ,U03Q4EESR,U03DVLEF1,U036CV26MMK,U044DG3MG,U03G8EZ5W,U035SP7META,U039QBMQGF8,U04GZAHP4VC,U02PEFNJF1S,U043N1ZKLTV,U03240PTYTV,U01HB3GB2CA,U04DA32US87,UBQEK82UR,U0323STUUD8,U02REQCGLAZ,U0ZKU7XUJ,U03EL9RFZ,U08CAP005,U03FZJPS5,U7CG5U1K4,USW8SDK6Y,U03G8HKST,U02DVV7JE4F,U1N3KUC48,U03KGBBEW11,UQPFENLE7,U03HAU0UJ,U02GTC6K4SV,U01ND4R6K36,U03MM07BS,U012DQY09M4,U04M3B8KS49,U03GB6C5C,U05RL5T4P0C,U02U6V6RZB9,U05RHN01UD8,U0BEBUZLM,U0260TJLLAV,U05RL5T6U9J,U03RFQUM3,U01E0CWJ5UY,U02SCE5KA4A,U05S6NM8JRE,U03MM0CK8,URCR3RXKJ,U1CBFJPS8,U05RWBYUF97,U02LDS711DE,U016ZLB0QHZ,U03FKDY488Y,U026MPK1F9U,U05R3718QUX,UG934DW5P,U04CP8YES13,U044Q3G1A,UQY98NTQE,U03N324A6,U6UEWA61E,U03HBL2HA,U02JVKRLPL0,U05RHK9RXBM,U05RB3A5R2A,UG8E2JK4P,UEPQMP6AZ,UHNRB0L59,UQFV99FC2,U9HFR4B7B,U02UD1PQ16Y,U0357NRDNF6,U03MQD3BU,U03E5RRAS9K,U01JBS9U8P3,U027EU7JWVD,U03MX3TR7,U04FS9YNR,UFYNJDZ1P,UQHBR75EW,U02J60714KC,UQSR8BSBC,U8EFM9JBY,U039YHX7JEQ,U02KW22V29X,UAYNDQSJK,U0352QFF5T4,U02SPK4BGH0,U0JB57E5N,U05S6NFC09W,U04SHD64Z35,U01KVN64BV0,U042FPHBM,U03MWNXFK,U38HBC2KT,URZNG0ECT,U0EKX9WMP,U01AA6DJ6UB,U01TDSYBD5F,U036PSR3Q56,U02FMNPBWJH,U02U7SXGJ3F,UQW55P3D5,UES7L6E87,UQMJJ217C,U034SS5SH7Y,U03S73051,UQM74BLNN,U02J2HE1951,U01ET9F2HK4,U03MSUVAX6Z,U03TC327X0C,U02E3GR4P37,U046196QCJ2,U03MKCB4Z,U03N9HUFR0T,U01CM71SA5S,U03JF1ALS,U03EJ8M91,U011HDA8CR2,U0474ALNN57,U051D5WTYBX,U6QP92T4H,U04UQKH0M8B,U02BRDN3GJV,U02SP5JP4EB,U01MWKPDZK2,U03E5HYGYEB,U04QZLPLR,U05RL5YREQ4,U046P8TBTLM,U05R36WFVNK,U05R36A729M,U03NFQB68,UQLNG640Z,U03NXKMRA,U13HJ2934,UNP6NJYGP,U03NRFC76,UQG7CR0M9,UR374ARTJ,UR9JKGRDY,U03500342TD,U03T329Q4BT,U01GRD5SUS1,U05S6N759TJ,UTFQPUN7M,U05RB478QJJ,UT8CBPDGE,UKR6WTX4K,U01BK0EANET,U033J4SBLB1,U05RWC9EAEM,U03MLRFHW,U05R36WDR71,U02SG85EL78,U03DUS0QY,U02H7GW9CV6,U03MZSYLQ,U024S60A6E5,UF7CFQX0R,U05S6UU67LZ,U035W5F8R71,U023T0JJ2P6,U01GBVAFRP1,U05RHKQN4SX,U044NQWGZ,UQCQBTB4L,U02J60CF3LK,U0257DHB5GF,U0NDY5PLP,UGLFT5W9Y,U032MMBAMH6,U02QDS96VNJ,U01B55LUF29,UDR47DDMZ,U04HAJYM0RG,U047EDFDL3E,U010NN11KEE,UT7HSFN95,U149C5542,U0NHB1EDU,UT58PDL0L,U05S6N1FYJC,UBQ6VMS20,U03LYKHEQ,U05RB3WENEA,U03PBR367,U05AXQMAPE2,U03MBSX5Y58,U03MKLGEV,UR0U0M7MK,U05S6N827MW,U05RHP1ENP4,U04669SG26M,U6F6X8Y3B,UUVPBJDN3,U8NKZMAK1,U03CL1JLP54,U045R23KU,UHSTL2EKY,U04Q60M85V0,U8T8AG83C,U1E124X0X,U05RHP15E3U,U02KKLCQK5J,U074A7ECE,U028Z1HEE75,U03ML46KP,UDDHSNRTK,U039879MSBH,U022QDQCXRT,U03DSDA95D2,U62JH9BDX,U023J4FG5R6,U04DBJF987N,U03MK3AFV,U03V9PNAG,U04UMFYDR9P,USMAX8JDR,U05RHP1MRK4,U047QPS87,USVANH343,U01CW7F4E1Y,UC0RKCFFF,U03MKADET,U03FKCQFZ,U03MLTC58,U0GMMJ814,U01ETAJ7MCZ,UQM2QGZ25,U030Z1PCLHY,U04GRC64D0U,U04G3JR20,U01PWEKHZTN,U03MW7287,U02N6TE2HJN,U044FJ31HJ6,ULSGD4RNV,U03MNEN7A,U02Q4PHS0VD,U02SPL0TDQT,U02DR0Q2264,U07T26K4M,U05RWBQ54QH,U01089MAS00,U4VD2HP4H,UAYENUJJX,UDRL1C4LV,U05RWBBRAPK,UQUTQMSPP,U05FNLL8U1H,U0185BSGKB9,U7AB4PR2T,U87N962F3,U0275GNU81X,U047MAELT0W,U047PMANYJZ,URSUJCZBN,UJGU3MN3H,U03MK4AV1,UHWLE8WER,U06HZKGBV,U05RHN0BB3L,U04PPURTJQJ,U01FN0RHU84,U02JB3F6VGC,U03KDFN0C,U9JTUL6RK,UBB0CB98F,U05S6N84U8Y,U03J22P6W,U03MLUC9Y,U0B20QE5P,U02PANW9RM5,UQE31NE91,UQTQ40KNJ,UR8ARTREZ,U5QQD12H2,U01CWDK9U4B,U05R36W66JK,URK5E8WLC,U030BH16DFT,UKVTFKHCK,UBCNC3A9W,U029BR53VFW,U01JR10V9N1,UR0CM3WH1,U04DREZ71,U03M7A0KLCS,UBAMPBC0J,U03ED1X8DTK,U03JWH684,U03NSGB1Y,U030NTWQK71,USG799ALE,U03BCR9KYCF,U051RMZ8LE6,UR8ALQT4Z,U03NN9DB3,U9S70HZ37,UQVR68XJB,U04HYQ85CJC,U04PA6B7P8B,U05RHKA3Y9Z,U01QZV2KRPB,UBV3800V8,U05RHN0G458,U03DVKL9A,U044QTWFY,U05RB4722EA,U02TESBNG4S,U3D0SR0UF,U01B72GFSSX,U01FC1FEGAF,UBVEAUGSH,U01FVPCKZ27,U03HXTZGX,UDH7JQXG9,UR7LH2E0M,U01SA8B50RM,UAY9HRA65,U0483QHTY0Y,U03MQ3CN2,U02GKKLV9DF,UR3DPASS3,U04AKG3T30W,U0312A8M21Z,U02KRL0P17W,U04G8Q9F74P,U05PHKDES0J,U043RC12USU,U05RHP1KDTL,UQRFTQEQK,U02330JPR8A,UBNENKAA2,U03DU0QMT,U05CUDFHA2H,U01HZC1E8HZ,U01AKPWSBC1,U018JSQ1D6D,U05LN23UY31,U03JR22SY,URMTC4B6D,U05F88G12NB,U05S6NG6T88,U033DGYJ1B3,U01D462H8PQ,UKPJ5EG9Z,UJEHE78JG,U03MM84T4,UJWFFMUJ2,U03KXJYNG,U022D7JLSJY,U0209MPNRPD,U02MFNSJERY,U0263AAB0NR,UHT2W429L,U2C1L86RZ,U05R371L015,USVAAHW83,U03LF6T2S,U03MK2KT5,U02T5QSR6KG,UQTRHHJD6,U1GMPM4U8,USE70S11S,U03EL8M1M,U02EAN5USSJ,U02MA48CHML,U049Y8F0X6D,U0D7X1T34,UNR86LG0J,U04SLPRPBQC,U01SW4NS4DV,U02J0H9150V,URU928KS7,U03PCR5BM5F,U03LUHNFQTZ,UU4TYGF29,U03PHH2D0LD,U02KWUX97GB,U05RB3N6C86,U01R9TS82JE,U03Q78APU,U02GNL6FV7E,UB0V9S879,US86TQ7CY,U45LT8MCY,U01FKEUNT2S,U02AZ76RPED,U021G7AGW1H,U044R1CH4,U03MN7EKB,U01K5C066U8,U03NTCA9M,U05NBNRLMD5,USMQGTQRL,U03NW5VFB,UUTUKNR2S,U04B22AK3GE,U029Z3D5GGY,U2L2X71J7,U05FTEJQ7LP,UBUU54X1R,U03N1RLJ0,U03UK9HUW3C,U2KH5NZ24,U03BQ1S5M1C,URFBWUH5E,U036C3J3UF6,U0DKU8ANQ,U010Q0V0327,UNZ7U5EUF,U02UZK21KT2,UGN4DFXNG,UB7SASSH0,U01ER5W96RK,U03JE7ERE59,U02LVJQLXHD,U02BWSXQC2Z,U03MMKWFN,URL460M09,U05TWQ1DERK,U016SP81546,U0MD0NU0L,UR5MSAX60,U05R36W8SDV,U03MKK3JR,U021YR2FVFF,U04H3MRSHD4,UCKBSD524,URKG6D5S4,UT6QQFV5W,U0130JCMV2R,U05R379V9V5,U05RL6DG4EQ,U03FKC42M,U03MS2216,U03MM7Q98,U5W83BSJH,U02NAJ2LZDK,UC05YKMJB,U031TN9H2DU,U03MVC4E3,U05R36FR3RV,U03LYPH7P,U017BD61J7R,U03NC7YTL,U04AS6AUQKV,U0F7NH2HM,U049K2PT6UQ,U8G5NJZFS,U03QGBCBJ,U030VT86UKY,U02JZA899QC,U05RHKGQ97D,U02PKHVE7GW,U03MMEXNU,U03MMKCKC,UCL1V4A3C,U05RHNR8F34,U9NC576KE,U04F9T82C,UA2EQ96P2,U02URN4DVS9,UBM419TV3,UEJM7PUDV'}, response={'ok': False, 'error': 'too_many_users'} (run `/slack debug error 82139495-b601-4fef-b68b-ba025485d876` for the stack trace, run `/slack debug error 82139495-b601-4fef-b68b-ba025485d876 -data` for the event data)
```

My smaller channels are working fine otherwise, so things are looking okay for the most part.  I also noticed that:

```
/query user
```

is no longer opening direct message chats as the old version did.  Not sure if this just isn't implemented yet or if the mechanism has changed in this newer version to do direct messaging.

**Comment by trygveaa** [comment]
Could you run the command to print the stack trace and paste it here?

```
/slack debug error 82139495-b601-4fef-b68b-ba025485d876 -data
```

If you've reloaded wee-slack you need to update the id with the new one from a new error.

I can probably fix this regardless, but I'm not sure how a `user_status_changed` event makes it load a lot of users, so want to check.

> `/query user` is no longer opening direct message chats as the old version did. Not sure if this just isn't implemented yet or if the mechanism has changed in this newer version to do direct messaging.

I'll probably make that work at some point, but for now you have to use `/slack query user`. Note that it currently only works for users that is loaded (e.g. has posted a message or is mentioned in any of the channels that's loaded, is in the nicklist in a channel). That's a limitation I haven't found a good solution to yet.

**Comment by nipsy** [comment]
I've issued the relevant command for the most recent version of the same error I had.  And after deleting all the duplicate blocks, ended up with this:

```
2024-03-27 15:22:50               Traceback (most recent call last):
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 6497, in ws_recv
2024-03-27 15:22:50                 user = await self.users[data["user"]["id"]]
2024-03-27 15:22:50                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:50                 return self.result()  # May raise too.
2024-03-27 15:22:50                        ^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:50                 raise exc
<snipped 21 repeats of the last eight lines>
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 479, in gather
2024-03-27 15:22:50                 results.append(await task)
2024-03-27 15:22:50                                ^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:50                 return self.result()  # May raise too.
2024-03-27 15:22:50                        ^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:50                 raise exc
<snipped 501 repeats of the last eight lines>
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 6497, in ws_recv
2024-03-27 15:22:50                 user = await self.users[data["user"]["id"]]
2024-03-27 15:22:50                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:50                 return self.result()  # May raise too.
2024-03-27 15:22:50                        ^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:50                 raise exc
<snipped 26 repeats of the last eight lines>
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 479, in gather
2024-03-27 15:22:50                 results.append(await task)
2024-03-27 15:22:50                                ^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:50                 return self.result()  # May raise too.
2024-03-27 15:22:50                        ^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:50                 raise exc
<snipped 1505 repeats of the last eight lines>
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 6497, in ws_recv
2024-03-27 15:22:50                 user = await self.users[data["user"]["id"]]
2024-03-27 15:22:50                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:50                 return self.result()  # May raise too.
2024-03-27 15:22:50                        ^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:50                 raise exc
<snipped 56 repeats of the last eight lines>
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 479, in gather
2024-03-27 15:22:50                 results.append(await task)
2024-03-27 15:22:50                                ^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:50                 return self.result()  # May raise too.
2024-03-27 15:22:50                        ^^^^^^^^^^^^^
2024-03-27 15:22:50                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:50                 raise exc
<snipped 501 repeats of the last eight lines>
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 6497, in ws_recv
2024-03-27 15:22:51                 user = await self.users[data["user"]["id"]]
2024-03-27 15:22:51                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:51                 return self.result()  # May raise too.
2024-03-27 15:22:51                        ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:51                 raise exc
<snipped 14 repeats of the last eight lines>
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 406, in task_runner
2024-03-27 15:22:51                 future = task.coroutine.send(None)
2024-03-27 15:22:51                          ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 6094, in _create_item
2024-03-27 15:22:51                 items_info = await items_info_task
2024-03-27 15:22:51                              ^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:51                 return self.result()  # May raise too.
2024-03-27 15:22:51                        ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:51                 raise exc
<snipped 132 repeats of the last eleven lines>
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 406, in task_runner
2024-03-27 15:22:51                 future = task.coroutine.send(None)
2024-03-27 15:22:51                          ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 5220, in buffer_switched_to
2024-03-27 15:22:51                 await gather(self.nicklist_update(), self.fill_history())
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 483, in gather
2024-03-27 15:22:51                 results.append(await task)
2024-03-27 15:22:51                                ^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:51                 return self.result()  # May raise too.
2024-03-27 15:22:51                        ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:51                 raise exc
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 406, in task_runner
2024-03-27 15:22:51                 future = task.coroutine.send(None)
2024-03-27 15:22:51                          ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 5421, in nicklist_update
2024-03-27 15:22:51                 users = await gather(
2024-03-27 15:22:51                         ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 483, in gather
2024-03-27 15:22:51                 results.append(await task)
2024-03-27 15:22:51                                ^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:51                 return self.result()  # May raise too.
2024-03-27 15:22:51                        ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:51                 raise exc
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 406, in task_runner
2024-03-27 15:22:51                 future = task.coroutine.send(None)
2024-03-27 15:22:51                          ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 6094, in _create_item
2024-03-27 15:22:51                 items_info = await items_info_task
2024-03-27 15:22:51                              ^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:51                 return self.result()  # May raise too.
2024-03-27 15:22:51                        ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:51                 raise exc
<snipped 368 repeats of the last eleven lines>
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 406, in task_runner
2024-03-27 15:22:51                 future = task.coroutine.send(None)
2024-03-27 15:22:51                          ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 6143, in _fetch_items_info
2024-03-27 15:22:51                 response = await self.workspace.api.fetch_users_info(item_ids)
2024-03-27 15:22:51                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 4136, in fetch_users_info
2024-03-27 15:22:51                 responses = await gather(
2024-03-27 15:22:51                             ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 483, in gather
2024-03-27 15:22:51                 results.append(await task)
2024-03-27 15:22:51                                ^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 269, in __await__
2024-03-27 15:22:51                 return self.result()  # May raise too.
2024-03-27 15:22:51                        ^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 289, in result
2024-03-27 15:22:51                 raise exc
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 406, in task_runner
2024-03-27 15:22:51                 future = task.coroutine.send(None)
2024-03-27 15:22:51                          ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-27 15:22:51                 File "/home/nipsy/.weechat/python/autoload/slack.py", line 4132, in _fetch_users_info_without_splitting
2024-03-27 15:22:51                 raise SlackApiError(self.workspace, method, response, params)
```

**Comment by trygveaa** [comment]
Oof, that stacktrace is messy. But I pushed a fix for the issue, so try again with the latest version.

**Comment by nipsy** [comment]
Yep, that did the trick.  Thanks!
